controllers/BookReviewsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use yii\web\Request;

class BookReviewsController extends Controller
{

	public function actionIndex() {
		$data['booksList'] = $this->actionGetBooksList();
		return $this->render('index',$data);
	}

	public function actionView($id) {
		$data['id'] = $id;
		$bookslist = $this->actionGetBooksList();
        foreach ($bookslist as $book){
            if ($id == $book['id']) {
                $data['auther'] = $book['auther'];
                $data['title'] = $book['title'];
            }
        }
		return $this->render('view', $data);
	}

	public function actionGetBooksList() {
		$booksList = [
			['id' => 1, 'title' => 'Web app', 'auther' => 'me', 'url' => 'www.amazon.com'],
            ['id' => 2, 'title' => 'yii2', 'auther' => 'myself', 'url' => 'www.amazon.com'],
            ['id' => 3, 'title' => 'mastering', 'auther' => 'And I', 'url' => 'www.amazon.com']
        ];
        return $booksList;
    }
}

views/book-reviews/hello.php
Hello Here y'all
<h2><?= $name; ?></h2>
<h2><?= $age; ?> </h2>
<h2><?= $city; ?></h2>

views/book-reviews/index.php
<?php use yii\helpers\Url; ?>
<h1>Book Reviews List</h1>
<table class="table table-striped">
	
	<tr>
		<th>Title</th>
		<th>Author</th>
		<th>Action</th>
	</tr>
	
	<?php
		foreach ($booksList as $book) {
			$id = $book['id'];
	 ?>
	<tr>
		<th><?= $book['title'] ?></th>
		<th><?= $book['auther'] ?></th>
		<th><a href="<?= Url::to(['book-reviews/view', 'id' => $id]) ?>"> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> View</a></th>
	</tr>
	<?php
	}
	?>
</table>

views/book-reviews/view.php
<?php
$this->params['breadcrumbs'][] = ['label' => 'book title', 'url' => '/book-reviews'];
$this->params['breadcrumbs'][] = $title;
?>
<h1>Review the book</h1>

<table class="table table-striped table-bordered">

    <tr>
       <td>Book Title</td>
       <td><?= $title?></td>
    </tr>

    <tr>
        <td>Author</td>
        <td><?= $auther ?></td>
    </tr>
</table>